<a href="https://colab.research.google.com/github/lsuhpchelp/lbrnloniworkshop2019/blob/master/day2_python/numpy_warmup_exer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import numpy as np

# Warm-up Exercise for Numpy

#### Create a 1D array of numbers from 0 to 9

- Desired output:

> `[0 1 2 3 4 5 6 7 8 9]`

In [0]:
arr = np.arange(10)
print(arr)

#### Convert the above 1D array to a 2D array with 2 rows

- Desired output:

```
> [[0 1 2 3 4]
   [5 6 7 8 9]]
 ```

In [0]:

print(arr)

#### Calculate the square of a 1D vector, then reshape it to a column vector

- Desired output:

```
[0 1 2 3 4]
[ 0  1  4  9 16]
[[ 0]
 [ 1]
 [ 4]
 [ 9]
 [16]]
 ```

In [0]:
a = np.arange(5)
print(a)

print(a2)

print(a2)

#### Suppose in an experiment, there are two variables x (from 1 to 5) and y (from 2 to 4), using numpy's broadcasting to calculate the matrix of all combinations of `x^2 + y` 

- Desired output:


>
```
[[ 3  4  5]
 [ 6  7  8]
 [11 12 13]
 [18 19 20]
 [27 28 29]]
 ```

In [0]:
x = np.arange(1,6).reshape(-1,1)
print(x)
y = np.arange(2,5)
print(y)

print(z)

#### Sum the rows and columns of the above matrix using Numpy's aggregation function

- Desired output:

> 
```
[65 70 75]
[12 21 36 57 84]
```

In [0]:

print(row_sum)

print(col_sum)

#### In Numpy, matrix multiplication is done using the dot() function, verify the matrix multiplication result by writing for loops:

- Desired output:

```
a=
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b=
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Using numpy's dot function: c=
 [[ 60  70]
 [160 195]]
Verified results using for loop: cc=
 [[ 60  70]
 [160 195]]
 ```

In [0]:
nra = 2
nca = 5
ncb = 2
a = np.arange(nra*nca).reshape(nra,-1)
b = np.arange(nra*nca).reshape(-1,ncb)
print("a=\n",a)
print("b=\n",b)
c = a.dot(b)
print("Using numpy's dot function: c=\n",c)
cc = np.zeros_like(c)

# complete the naive for loop below:
for i in np.arange(nra):
    for j in np.arange(ncb):
        cc[i,j] = 0
        for k in np.arange(nca):
            # TODO: complete this line
            pass
print("Verified results using for loop: cc=\n",cc)